### ISSUE TITLE
2-Agent HalfCheetah code

### ISSUE THREAD

**Issue by SigmaBM** [dkkim93/meta-mapg#1]
Hi, when will you upload the 2-Agent HalfCheetah code?

I implemented this part myself, but got 100 average reward for agent i using Meta-MAPG, only half of that shown in your paper. Maybe I missed some details. So I'm looking forward to your source code. Thank you!

**Comment by dkkim93** [comment]
Hello. Thank you for your interest in our paper. :) 
The performance difference can be resulted due to using a different meta-population. 
I will upload the source code along with the meta-population that we used in the paper by the end of this week or next week! 
Thank you.

**Comment by dkkim93** [comment]
Hello. I have uploaded the 2-Agent HalfCheetah code to the `main` branch. Please refer to the updated `README.md` for further details on running the 2-Agent HalfCheetah experiment. Please feel free to re-open this issue if you may have any questions. Have a great day! :)
